var htmlConfig = {
  bookConfig:
    "v010001102f46KToyOcnwGYl1Aav7LZlxDYkwFStyLbh8PZu8LUuuCbr2JUmxCemyPbo4Kci5Gbk9ERkzFZj0BSnyNXnwOSq9Fdk8Nbo7GfkyCbi4Kbk8OZn9EbtzDfj6KRl3Pak6Mag3AQi2KSkuIct6Bcl3EZg9ARk2OXh4BfvvPTsxFTs6ISg4NbuxOeo3AdjvJRkvIQl2DQhxIQn3PdrwOSv7NZm5EQovFVs8KSqzIcp7MYt3DTs6BRswHbu9PQm6ISj5FUo1MWvyHfi4JdswBTn5EYp8KajwOUj4AXp4GcrxIWn9JXj3Jai6MUj8NQq2Mat0PZkuNek3ARvzBSmxHRpxBXkvLdi4KXm4CYt1NXvxLdnvAbo0EXnuHfouDbizDQj7FYpzNSj2DbnxCbquAZrvAen2BahyGctyEdpzGVn9CYl0DQsxKbq8Abg9Pbt2Dep9FWsxHUo1Adm0Jbn6NZg5FWt5Nbq1DTr8JTrwMcp2Ict8NZl4JXn7DRq8NYtyGdlyOVlwAbn4Nar6NTm0HUr8EYg1FSl7HZt8ITu7HVm7MVjwJSq8NYizCchuCQs7BQo8CYovIdtwDao5Gch5EZmwEfsxHfozBYq2CQp0ESt5Nek3NciwDWsyEdj2LQh1CWh0EVm1Bcj9JRj5FTq1KchuIUhzPbj1BfmwLQq3Gas6KQvxLUr1Gci2NRv1Pbk4EWv5DSu1JTq0LdqyCYlzBdoyPWixEbi9KTnzDYu1IRg8Bch6MTvyKYj8MXuyFbhzCSk4MWl2OdqyJar5LZouJahwHWu2Dco1LdixIWqwCWl2Ocj0PUrvJdvxMfr7NdnzEYs6MTp1Kfl2MWnyKRv0KanuJYm4DVs3KRm2CajyEXo7KXm0BRr5FesxITk4KcrvBYjxPftuCSuwAav9GXu2PYq7Kbs0BVu9IQmxKdkvHZnuHUm4NfryIcqwJUozGSvuKbvuLemwHfk4PVmyNYm5NVjuCcq0DeuzNco1Ebt5MSs4Kch6DekwLdkxDco3LYt2JVuyDUv3IUq0Gej6Pds5LXl5IUo2PSv9Mar5AYr6JflvBWhzAQt6OVi1Dck6Nbr7EUj5DUuuMeo3AZk2OSn7OUj7MUqyEbjvLbpzGdi0Bbi2IVs7AZjzBfm6CWn3NYiwCYp6AYj5GWs6EXg5FTlyAbu5GbmvOTsxOVm0Abg9JWnxFVn7Jel3CZh7IWh6Gah4ARtxFUl7Kbv6PepwGSn8Ofj7IYqyFbu4AQr3GXkvFZj9NblzOSq7ObizHSk0NRv7NUg9FTguMRt4NXiyHco5EcryNfv9Cal0KdsxCYn0Gak8OZu0NZj4GWq0OQtuMaivJWo3IVjuIXqvKXh9Hbm3GYhwPYg6Cdh8ISp4Hch4OVj5IYp5PWlxEUjwMSu7DXt6BYj6ITruAWiuFQs2Pao5MXi9DWi8OVr7NdmvMWi5Pam8NejwMVsuMZryNdk5KQi0BUpuKfo4NalxEXpuBdt2Ddr9HQjuNXk8PQl4IXq0LYn7EUvvGZv8AUr6CVm6ARo8FYn0GYq8KUvzGUi7NZgxCSl7Dfj3IUhwEctuKWu8Jcs0IdpuLYs6NXkxGdq1DTk2IQizCSg8CRtyCVv0Hfg5JVm2CXq8HVi9MWh7EZnyAbl2LQl1CTpyKYu6BVh9FflyHdtyOQsxJbq6EQmuAXkvHQo3PZi7Kcn0AYnuGYj7NXq6EYo4PRp8KcoyKbp2CYg0LSqzGdj5JWn4JdizOWs0Dah1KbmyNasxHdq9IVl8GbsvDdq5GZouFRhyEXg6LTkyEcpyDUgvDSsxAfv8MUu5EYoyPZkwLXnwJbkyNWi9Nej8Gbi3LYk6Beo7AUj3Gcl0JXizKcrwJcl5FVp4KTj6KQszDWlxPeg1Mep3EWl1PRhwBZmwKZozOXl1MasyCVkuDSmwCbk1AcoxDQozJdsyEdgxHZq6Obk0ObhvKaixHar5HVt3CYh5Ibs3BdlwNepwCdo0Abm9DUp4NZvxBUo2JamyGao6HZr3KWvuMcp7LTjwIVi9ESm1EYtzFcsvIfp3ARj7NSi4Iam0IVr6EctxIet3AYr4PQl6GUquEVs4CZlxJRg1KVu2BWs7OQk4NRivPVh7LbiyEVm8BVsxCRh9DSq8MYo0NZj5Aei8KXh7CbvvMbv9Pft6CYo6DWt5PflyFekuEZnyMSjvKQswLQt9Mfg1KWv3AXt6PQh4KWg4DcozDSmwIQruPVj5EShvKZguAbuuPZt5Fas5IVl6JQkxCTouPfsuBTl8CYr8OVn1Kfi8IUkwASr1CZmvMVsyETg2DWr8CRtwPZu0CaqxHUlvOQt5CXg5FSqwCXq7EaqwJdu5OSq0Odh9EYlwLch2DamuDTv1HRmwDYnwNevzNao2JUi1EQu6OXp9Jdr0FVnzFcpyGSg8NSpwIfr0MXh9Fbg2LZuxAUnuJbg2DQm1GVgzAcoxNRq4NYl2OVtxKbm8LajvAer3PTj7OXp6Nah2Ldq4LYg2BTozMYj8MUv4HXtuOWv3GSh3IQh9IWp4IWv5HUjwHYu3PSg3LWm6EUn8DevxLbj4Hao0GWg5Kdn4Icg4IanyBZm6EQt8IfhuFbsvJWp5Hds3HWp2GchzEeiwATq1GWv1DfovNUm1Kao2Icm3LbkwFTuzEahxMWjyCUu0ITi3NSv5AXpvIar5JdvyEUryFbquMft8DajuNZt3GVoxDev0AcmuFQozFai7NWi1HekxPci8BUu4KYuvJTjyEfvvJRs4KYv3KWvyMQizBXo8ATm6MQmxAXg9NahwCdkzOav1PVpzLTkuFdv9LYm2DasuERpvCXu1Een1Gcr4FVkwDbuyKYr3PYu9DXl1Cdn8NRl4Ieq8HSj4CUo1MTiyNXl3IZhwBZr1HVh9Jbt7PXg7IdnwAcl2PSo1PcixAZsyNbk4MTs6ESn2AZg8FQtuPZg1MSl2MYs8Hbu5MRpvCQq0ESpuDYh1JUt9Cdv6MYi5Icq5ERgzGRj4Gbo9IUt1PVtxCch6BZjxNdozBYpwDTpvDUm7Lej8NYuyFei1DSvxHZouOYpuOSn7KQovJdsxKYr6OSgzLTrzEfgvGap7PekuFTp0PWk5GRjwAbg4Oat0EXu0Oes8LRg0BYmyPaqvITq1Nen8Dav7FQn1Ket4Gal7OWj4HVqxIZq5Hbq6CUt2NWg5LbuvNUk7Edj3Mdk8KTnxAdo8ESh3Geg1FXhuIYr3JQtuERo5Nfv6JSo6EYj9JUl1Neu0JRj0FWu8HVn3NZt4ASpuLbj6IRh1Efg9IXj1PTr4PZv4MXlyEStyHSqzMRl8MSp5NbixOcl7NVnuKYu0CRh1Cfk4Jdm8CYr5HfkuGem7JXt4HUquAQt2LYmxHagwEZg8MQo6JUg8EQv7JTgzAXr9PckxAWv6OWo8OQgxKUp1Beu0NXiuITr6JSlxKSq8JdjzDej4NWh7DTivJUmzHUk0CQsyKVmvJao5IUtuFXi9Icu2PfhuNbiwLdm2OVo8MTquHQszMcnwKcg1FSgxMSn9ITtyOeo6HYi3JQm4NZuuHXrwBZn4Neq0GUg9Caq5PRtyFZn6FTtwEdj3CXq1FRiuHanvPYmuHblvBeryJTiuPakxHfl2DXs6Hfi3IYr1Eah0Cch0EYq9HfkuDZivDcn3HUtvGUi0LUt8ESm9KSg4Eap5NWo7Edk9PckvIWpvEUl1KYq6EVlwMWmxBSu7EQt8LaozPdmuEYj7FciyMRs7FVt7HfuzBag9PYo9KavxLTnwObn2CRu1ATpyPapxBWi5IXg9KbguNSozCTgxDcguOcr6JVvwLVp3MWm2LRh6Nfo8PWn3KWq8CXv2Jbs0CZg7KWj7LTluCdg6Nak5EblzIat1Mcv3Gau3KVs4Cbi9BUlyMcm9BfgxHanuNSm1Ffq4Cen1CVp1Abp0BWpxLZt6ESixOXo9GWgvHZuuIck2Dcp1GauyGVr1MWq9KYlwETmxAYr8OeuvNYk5EVj2HbtzKcivJXjxLWo1PUi1HZv3NfhxBYl5Jar6LSrwObowGUvvJYnyLVivJes1EShzHVh5LSqxKVj0CQg8Cej4ManvARgvLfs1Gbr1HQuyEUnxGft3JWg9Hcl6PSszFSjvMXn4GRh7IaizLZr8Ebi6MTqwJYr9DVsyMSsxIRt4Afp3Cdo9Hcs7Gbm9Odv3BRj6DRg3HVnuGQt3ERq7OfuvDUtuOVnvJTr0HUgvDWuyFYkxPcvyETtuMakxKfqvBUs8ITsyPSn6MZq7IZt6GWjzDeu7FWj4Abs8BRovBemzBQn9Pag9OcovHStuGTrwMVmxHfnuEds9NZq1GYjwIXkwCVv6FcnuATgvPfvvKWlvORt7Lfl8LQg9KXm6FcuxIdv9Jbr6Ddl3Kep2OahyDYt9PfqxDbn6OYl9NalyCVs6Ibq1KYj9GSn8BSv9DdnxEdv9BZi6Nel8Lav9NeqyAcn1HYu9Bfv0MVr5Cep5DVl0OXgzNfhzGTq8HWuzNco5DYi5Jap0Jbt6NQt3EaruLRo6JbtuLQlwDct6EZm6Bdq3MZp1FejuAUh3KVk9KdjzIZj7PXt0DVp2AaiwLVo7HUgzEduvERlyHVk2DSrzCQh2Gdv4MVn8LbtxNQl1HdpyGTp6ARuxKZq9Mdg4GQp2FQjxFcg8MTtwEbv9BQs7PRg1CYgyPWuvCVuuKdoyEbnwGQvzPYhvGUk1Ier9Eal2Oej0Hcu1Nck3Pfp3AZm9CehzOcr5LQp7HWg6Idm1IVr0IbozBcs5IUk2JTl9LUm7Ofr0BXk8IZnyHch9FdouDWnwJdowKTgzLRm4BdswAWm5DZsvCeruLThzCYsxNWi9FTlvPVl7GbuwJUh2Ccm4DUm2FalvGbi9HSkzDRo3NYj0OWs6DdnzLdq0NauvIfmvMdt8HVkyIfhuBbh1Kah7BSluIeo0EUn4Ddr0LQv8EZjwOWgyHdq1BTt9Fbl1JdnxJfmvKSrxKXsyOcjuJal8Odn4JXrzHWm4NfoyARuuITvvKSo7Pek9AVs8AQs9HdjvHeh8CZpyIXs6JUuxOcj0ERu6PXs2Der8Dep3Pcn1GUpuOdsyJXhyNYlvKfpwIbr5NQh6PYo7PUovIZs1FYg6BfuwJTs9JQv2FWmvJdtwOZh7Deo5KRi9PZs2Nel3PSv1HWj3NQjxFYq4Mel4JXk6JWizNSrwHTj0BUjvEch0Cbv7HRhzHWpxEch7PXl5Naj9GSgxGdp7ORm5Iei4JVvuDVh9OYi8OUv5NeozNes2ARm1Hbn2KUp4KXm8ObquNav2Pat2IVj4DZq1Ich6BYjzPcs6HRv7DUs3LQp1MUnvOTjwNXg5Iar4Pej5NSu6Bcs4HQh7LalwMdv2AQi8NcuwCfh0LSo4HUp6NVl2AXnwFdvzNQkxDelwJctvIWoxGYm0PZq5Lcl1Ack3IRk2Aci6Cbq0GbuuPRp7DWp8OfvvEZj0PShwKfv7IZi1Adt7HXn5Pai9CYqwHVv4EVi3Gek2EWh7BYr9Gep5ITgvKWuuITouKRs4Gbt9LRp9HRpwCak0NTqxNfm8PSo5DblvGXg5HTjuMau8HdnxIVk7NUuvAbtuIXs4ITq0NVp8LZp6GRk9PejwKTn7Cbi4Bam3OTo4KYo6GUu9Lch8HXj9LWmzHchzNfr1MVm5CbgvISt8OWs7Gcu9JSv2DRs4NSr0LaqwJYi4DStxHct5Ceh6Ibn8DfquJVl7ARk5Hcp2Caq7Keo4HXnvJXk5MWnvFRs7OVh6LRs1IYp2Ieu1Kbq6OdvvGbn0KXhwPWm3EQq4MWjyJWm8FdkvEUs3Lfu6MZu9HchwOVhuGUl2CYr2NYn0GQr2Kev4AWj5PTouFTj5FXqzEes3JWr7JZr5OWh5GVn7AemzDVvwHanzBXh2JTh2AVh6Kcg3Cdj6PTtvFWkwKao0Kfj0GTt9CXq0IWr2JSnvFQo4LQr3Jct1IVj9HSv6ORkwDWivBUg9HZtuBZj9DbsuPdgxIer9KWrwOTvwFYtyDVn3BctyFXu8ETjyLboxBYh8EVq3PTowPQs5KWtwEVi1GVk4IcpyBWg0OVr9ISmxHWpwMVg8DYrzLQtxFQv3Ldg5DTl1HSk9CXkxCcj0BdrwDdrzNSl3PZl0MQt5Bcv2IYq2DXpyGbg9Gfg4OZp8HSiwCQt0KTgyIdm6Mfq0DXh2HanyPbt9GSg3Cfh4PfqwBUn0ORv3FWrvNdvzPRr6CYnxCcj0Jbp6Gdm0OQh5LXo1Mem0EXm9CVr3JXk6JTt4ASmxLfnyBZu7JXo7CZs8CUj2NVtxCWk1Mdn1Pep5Mfv0NRs0NWvuLQo4CcizNbjyAXg9DYhxGQu0EdgvEZm6JZpvGdqxBYr6Fbn8LXt3Oav9Dch6MdqxMWi5MYv2HdixPegxPVo1Fen0PWtxLQu4PYj0OdrwOdizBQuzJWl4Ccs2MXm9CRv9AYhzAXnyEVmvNdqvEQs6DUq7ITu0CXq2MQg3BQh8AWj4ASv9IUp4HSm6ITt9Jan3PZgyFXh4Abg4Lem9ISm9MXrvFcp6MTn4KbmuMdu6OUl4HXluKXlyAft3Nan2JUo5PbhxLVm2KXr0Kfm8GZt1PWk5ETn6AVlwBZvyIdlzOVl5EYr2PTu0Cai8ASjzEWjwKTp6Jfn5BdtyKejuJfp9KWnzJWhvEUpuCVh8NfnvMRu3PTk0EUi2HWoyNTlwOZm3JZuzCbizBRvuHdvzKUk9ARgzNWgwFZrzDcp6MTn7Gdm1NaiuLXr7JXuuCWs5LcvwJXu7OYg0NdqyGelzKQu7Gfs4IQkvCco5KVn8CVhyGTn2ASv2LRtwKZm9Edi8KSkzFVq0JbrwIWs0DZp8KTkxEYoyFRiuNRn4KUp1CVg0KThxLTtwLei9KRq9JTmxCev6EdiwNdi4Jbo0OWtzJTkuHeq8HTg1CYv3JXk7IUg5Lfm7DRuzDWu2BbruARmuKYp5CWi2Ift8BRiuDUn9Hek9Meg2Lbo4Dbq6ARguBdp4FXs8NVm1Mdq9Gdh0HUrwAcm5NRnyAcl1OTp0CbuzHajvNep1JYkuLfr9NWuwGQsxASj2Dcm1ISm9Bdq8MZp4MQl2Pbi4NfivPYvvMQg2Nas0OSuyFTiwPeq0JetxDcgxHdkzPUtvCXixIanuNWq1LZn6DWkuEUh6KSj2HZjxGSmyFfh2Cbp3Les8MSluPXqxAQp1DTtuKdquOQvvBSnyIdu4IatxKXkxEVo1Aek2KVv0Nfl7BWj7IUu1GbqzJbsvCfgzKQmwNWhwDRr1DUhxGes7NTj9CWtuGcj8OXl7FVs8IUi6HWrzDUm0KYl9Maq8CStyJUm4Jau3FRh3DWo4Iak4PVsuFSi3OatuNcluBUu9Eav1Dfu1MUjyMcn6FUi9Nap4BYguCZr5FUj1EctuIav3PYqxCch4Lei6Ndi6EVkuIUg3Ndq2IRu8FZm4Nep9FWk5Eej0GWi2ETv3KSv7Mfo9NfqzOSu1GVq4JXh4KTl3Adq7DTj0CToyOSo9AQquJWhvLWjxGZi4Idq0DZmyDZs5Aep7PXp9Adi3Obh8NXh7Acs0LdkzBQkxIRn8PXo0GVpuLbowGQq3ISv7OYqwMcs6KXtxMal6Aek1FVtwNRt8EZh9Fdh5JUnyJQi6EXj8OarvGTl6FVr2IWv1HZu1JWv8BQl1Ebn7Pfh0AQtvMWr9GTnuMekyAVu9MZm6CRo8Kbr2EYnvIav8Ebs2PYtuIbjxKXpuEQvvJYhyPYm2AXryHcozGej0Dfv1GWs0Jfh8FXq5ESt2KRo8FSixJbs1Peo3OQm4NQh2JRp4MQv2OXovMcm7CQg1BaiwJSm1Bft6Iag0DZq8LQoxGfkvOWp1CZszCdswIbj4GchxLWn5CYuzNaiuOXs9KZmuESn1DWvzNXk4OQvvIZv0JfvxBXk1BdhwCfpvCdr2NduuBch9Pbq8DWk1IZq4CQlzMYvzNYg4Ldg9Abu5ITi3Gat5EVq9IZouMSp9Ecu3Icv1Kfq0Ibp5GTtuIUk3EVgvMQu5Gag9Acl7BYp6FegzPTgyGXr6Adl7OTquBWkuHUk2PdmxJSn8JdjvObuvPQr5FSr6KVmyHXtvPSq7Efv8NUj5Obt8FVnuGTtxOYvzMRtxCcrxAdv9HUkvKWj0JZpwPRn4Mdp6CTh8NTlyGSk6Kbu6OejyDWv6NQu6Gci9NQpvBZi9MZv0Fej9Lel2BXuwBbu3HUj5NVr5Idn1PYk3PWn6PWjwLWgwOfrxPSu9JepxGbouNSi9HSpvERlwGUp5Abh5MfryJWn5BXo8PTk7Cei5MXp7NVtzOWr5Ebv7FckwCet3OVvyLSqwCbv7ISguNfu7JUozKWuxPfo3GSi4KVm1LSu1FWh1EckwHQt4NSowNXr4ASrxFUk8DSlyDaj1IQj6CQs3JYr6NZuxEds8Fdj8Lcq8Hbo2Lav5CTozGZj7FRjyEXs6Cdg6HaruKVtxPUuyBZj0CYr3IWn4LdhzHYl7Obu1Mai1KZi3KYlwHRhxNXk3Ocq0HYmvGXgzDcu7Pbi9IXv4OWr2PenwIVm5CYhxKWm9BRn3ORk7HWvwAXh5GTpwPct1McgvDVruPVm3BYnvOXj7MbvzLRj7OUs1LVuwIVm9DdivOcqvEbhwGTr9OUuzFdk4DSk2Gas9Bei9MRnuEZsvKWk0EXjxKRk1NfkuJduvCUnuLfh6Fev3JWj6LakuFeo3Fbi6Oai0NRn7IZjuJdn2Ceh1BaiwNVhyLeqvDViyMRp1BXo3Lbv3Ofi2NVuyIamuAas2LTu0OalxGbk9AWg5CYn0LRr8Kdk9Hek4MVh1CfluIaq4ERj5CQmwHRvwNej2LWu0JZq1MXn0ARh2PXr7Afh8NamyKSgyHbj0DXr8AUm3Icg9MTk6JemuFXg5Gav6PYs9EVkwBat0Pdl6LWj9OTgyLbm0NWhyGXq5HWh0BbuwCci1PSrzOSi0FQsvIXu1ASjyNWu9MTjwEepvGYivGTt3IZszPcp3BYj6IRu5JQgyEUj3CWg8CUg3GVu7JRj5HWp0MTj9NWs6Kfp2HSquIch8DRk5ESv8DSmxESmuAWo3BVn0HXovMYl5LXg9LVn6Dao0PWk6Len8AVsxDRl1Cdu1MTs6GXo0FTh0CauuLSo9MVv2IUrwCQp7CRixKSvwJahvFZs7HRsuKRjzCRv7Nbj7AfruNemxJbv3Nfu2FVj0AQi5CSmyEfquHQkvPVmzGWqvFet5KdmzHdhxNTgxDejvMRivKYvzPdj9NdhxMRm7NTh0JTpyLdr1MRguKdpvPWs7HXv0PSp6ATs7Ffs0Kbn2PSj8NZs0Bdi2Hbg1Acj1CRizJXr6Feo2NUm3Fam1IcmwCat7FRq3OSq1Lar4JYsxJXm4BTi5CQs0JQh4ASj0FUh9Mem8FZjyAauwNSr0EWq4MTn0LUh1ITj7BQn8Nas7AbnuNYpzMfg3DQpwDVsuFfgxAcgvIdmwCchvISq8AZr7AWkuNaq8AUv4Oah1CVh9Bfh5IWk5Jfv1FWo9Fen7BRsxDXjuAam0Lbu5IYjxNdn9BeruOcoxPQu5ETr2FZsyDUt8JTqwGRs5Bau6KVv0Fai5MUi2BWi4FSlwITt9KYnuESpzLVkvCRjwAWq6CUi1HSr8KTj9LUv3KZn1LUt2KYi3MRl7IfhzGVh0KTh4EeuyLVvyDXl8DQkzLVmyLSgxMUu9BZgzHap9Per4PYu6FVixLcr9Ibs3AVs8KZj4PUh0KYrxCdnxLUp1Hfv6GQnwIcn8EZm6Odi6CagxIcq8BVm8Pcj7Ibi7MVj7Mal9GbrxFSt4Adk0Ffk0HYv0GWj8NWguJas8Kbu8Bar7CWr7NUk7Kan7KVkwFZk4LYr9BeuvCZvvKekzCdo9Pam5Hdi3MQr8HUg1Eai0Nbj7Jdr6OdlzEcvzMXj2KUizGYq7Jfq5KUq5JUmyAZm9Dcq1Ido0NYp3Kfs3AUi9ERtyAZpuKTiyIfgvOau2NUq0EXuzOVm2PUh2KVu6KVjxMSpzJcl6HUs1PRi0GSuvIXm4Cft3DUk7HUh0OSnuKQt5GXsvBWmxOaiuGTguHTq7Iap3Cdt7IasuDdu5MRn7Act6Lfh7Kcq3MagwOatzBct3Fcv6GZv0NTk0JXg2HeuwBYlvMer4FQv6PZs0HQm2GRkuEep4LVj6Car0BWhyBbn6FUh4MfswNRlyIaixCRn2FQr9KQiuJek7AQs7KRq2DXs9FXjzFbt2JZoyETm0Aat2OZqyATg2EUj8CWh5IQowKeh4NYuxIaouBSp3KblxIZm9Ndl7GQszOSozLZh8Kaq3HRtvGbjyIYj0EThyMQvwCRo6PTn7Obu4FcnzOfuxLbn2OYn0HQixDep3Efg2KRtvNQh0PYg2HQvuHSo1Bcg9OahyAWi0OZgvASiuJan5NbjwNam2DQr4FXm2Ifk0NQv7DTo2FRq9JSgvOds5AYl6OTvvIdi2PWnvPYg5NWh4BTg7LYp6Gaq2DXq9GTl1Gas1OQv2MSmyFVi9PTj9OYgzAfkwOcn6OZs4NdhxORnvKas4LWn2HVq9AbqwBbu8Kak7PRt2ATq4Efn4DYg9JRsyJZhzHXowKZs0DVj8OYt7OZn8EWg9PegzCfj0EYg6DQk6Heu1NQmuMRtyFSk4PTp3JUquDSq1Mfs0JVqxGUo9LZpxOfowNZr7IYnuEVsxCctyIVj3NYrzERm7IUqvLRv1ATs3IUuuHVkzEZkxDSq8PZswHXt4CelzMamvPTkyCXn2Kbo4GbjzMcl0HVrwPah5PVruDUu2GWp2GTk3IRo5MRr5CfnwLfk3HVmxMRh1Ocm1HamzKTlwFbk4BQh9IVp2Ebi8MSqzHWvyMVuyFQu6BXkuLegyEXh9DQruGejvFZnwPTqzKctxMXl7Ieo7Kdu2NRmzAakuFdrwLTrzHeowLRgzJWm7OSouIciyOYs5MYuxATk2IXv2Cen3CRl0Fbg5GRl7MTu0JXp1GSs7BZk4CTuxEYp3GSrvFTh0NXh1Ibg8FbjxKWo1LVp2AZjyMahzJWivCWkyJSs2KVuwAfiuLfk1MRvzKSq3AUv3IYn7ORuzLXrvJXi5OZl7JTi6PXt8LXj9BRv2OVl4BUvzDSh0ETuzPYq8MYt0EUi4IVl7AfnyBfq9JTs2LcrwGUmuGVt0FTkvPTi1BTi3AbmvGQv2AYnzDTpxDbk6Hfn4FYsuIRs6FSg5Ddh8HXs6Nai6MWm8PYhyBUp6DRrwNQu1JRu7Kat2LSuuORl8AdszPRnzCZn6HUl3AWj1EYq2Aai4Nav2OQp2LZuwIQn3FQm3NXowOTnuDcj6AYuvCZozNTj0DamyFam6LUpxDdq6BYi0JSmxBXtyOQs5IauwKZp9JetvJbq0LUg1CXm6OYj4IRs6MZq9MTv3Odl5EYq3HaqyJWiyPRs9HRv2CdrwMYn9MVt4MYrxMbn1DRnzGYv8HahwFdp8FWl6ASk8IVu4JUh4AWsxMXr6PXj4NSnxMciuISl7Nau4PZuzNaouPRo7NbuuERt0ASn1MUh2BZs6GflvCQj4Ham1IXu0KehyMfl1DTpxIVquARu0JUqzMVs3LYkxNXp4GRp0Cbp9MVg3Dam8KXjwJSq1Kai3KTk4BVgvOYs7OXj4NQg1JZm0Oav1NVpvCSl5MXl3DVl7ESs7AZuzOfv5Lci2Fen4AZsvNanzFVs3Eak6Edg6MUv5EZq5Hdh0GWq4AZl8GRg8JYg7KSmzEet9Ffn9GcmuNXkvFfk5IYkwCbt6KRuuDYlwMcl3HUqvEXi6Fdt8EUt8MQn9ETj3MXmvMcv2AWtzPRqxIWp5MTn3JYmyBSjzLaqwPRryBapzEQr0CavuDclyJSvyBZj2BQhwMcp3HetxMQnwPTs8MRmxAYjwHfk3EVp7OfmuBTl6AasxHYvzBfm4ASq4AclzNXp9NWs4IXvxOZq7CSrvIeo4AQk3LTgvHXm7FVg9OauwHRnvFYr7AajzBdn6BSvxJZv4PWo1Heu1PVo2JfgvBWszPaq7AXs8Mfo7Ndu8MYp3Lbt1DSr8JRt4ATnyIbs7Ndg9BQu9OamwOTl9FTlyIYhxBVl4HYv6FSp4PSn9Efk6GdlzGUl4GXm5FakyHQm1FVjzgOab2d8fb48d854e24c1d69c043b4349c820",
  aliasConfig: {
    appName: ["", "", ""],
    totalPageCount: [],
    largePageWidth: [],
    largePageHeight: [],
    normalPath: [],
    largePath: [],
    thumbPath: [],
    ToolBarsSettings: [],
    TitleBar: [],
    appLogoIcon: ["appLogoIcon"],
    appLogoLinkURL: ["appLogoLinkURL"],
    bookTitle: [],
    bookDescription: [],
    ButtonsBar: [],
    ShareButton: [],
    ShareButtonVisible: ["socialShareButtonVisible"],
    ThumbnailsButton: [],
    ThumbnailsButtonVisible: ["enableThumbnail"],
    ZoomButton: [],
    ZoomButtonVisible: ["enableZoomIn"],
    FlashDisplaySettings: [],
    MainBgConfig: [],
    bgBeginColor: ["bgBeginColor"],
    bgEndColor: ["bgEndColor"],
    bgMRotation: ["bgMRotation"],
    backGroundImgURL: ["mainbgImgUrl", "innerMainbgImgUrl"],
    pageBackgroundColor: ["pageBackgroundColor"],
    flipshortcutbutton: [],
    BookMargins: [],
    topMargin: [],
    bottomMargin: [],
    leftMargin: [],
    rightMargin: [],
    HTMLControlSettings: [],
    linkconfig: [],
    LinkDownColor: ["linkOverColor"],
    LinkAlpha: ["linkOverColorAlpha"],
    OpenWindow: ["linkOpenedWindow"],
    searchColor: [],
    searchAlpha: [],
    SearchButtonVisible: ["searchButtonVisible"],
    productName: [],
    homePage: [],
    enableAutoPlay: ["autoPlayAutoStart"],
    autoPlayDuration: ["autoPlayDuration"],
    autoPlayLoopCount: ["autoPlayLoopCount"],
    BookMarkButtonVisible: [],
    googleAnalyticsID: ["googleAnalyticsID"],
    OriginPageIndex: [],
    HardPageEnable: ["isHardCover"],
    UIBaseURL: [],
    RightToLeft: ["isRightToLeft"],
    LeftShadowWidth: ["leftPageShadowWidth"],
    LeftShadowAlpha: ["pageShadowAlpha"],
    RightShadowWidth: ["rightPageShadowWidth"],
    RightShadowAlpha: ["pageShadowAlpha"],
    ShortcutButtonHeight: [],
    ShortcutButtonWidth: [],
    AutoPlayButtonVisible: ["enableAutoPlay"],
    DownloadButtonVisible: ["enableDownload"],
    DownloadURL: ["downloadURL"],
    HomeButtonVisible: ["homeButtonVisible"],
    HomeURL: ["btnHomeURL"],
    BackgroundSoundURL: ["bacgroundSoundURL"],
    PrintButtonVisible: ["enablePrint"],
    toolbarColor: ["mainColor", "barColor"],
    loadingBackground: ["mainColor", "barColor"],
    BackgroundSoundButtonVisible: ["enableFlipSound"],
    FlipSound: ["enableFlipSound"],
    MiniStyle: ["userSmallMode"],
    retainBookCenter: ["moveFlipBookToCenter"],
    totalPagesCaption: ["totalPageNumberCaptionStr"],
    pageNumberCaption: ["pageIndexCaptionStrs"],
  },
  aliasLanguage: {
    frmPrintbtn: ["frmPrintCaption"],
    frmPrintall: ["frmPrintPrintAll"],
    frmPrintcurrent: ["frmPrintPrintCurrentPage"],
    frmPrintRange: ["frmPrintPrintRange"],
    frmPrintexample: ["frmPrintExampleCaption"],
    btnLanguage: ["btnSwicthLanguage"],
    btnTableOfContent: ["btnBookMark"],
    btnExitFullscreen: ["btnDisableFullScreen"],
    btnFullscreen: ["btnFullScreen"],
    btnHome: ["homebtnHelp"],
    btnMore: ["btnMoreOptionsLeft"],
    frmToc: ["btnBookMark"],
    frmSearch: ["btnSearch"],
    frmLinkLabel: ["lblLink"],
  },
  meta: {
    htmlTemplate: "Popular",
    theme: "Default",
    title: "GIỚI THIỆU TÍNH NĂNG",
    description: "",
    url: "https://online.fliphtml5.com/jhqln/qzuk/index.html",
    pageCount: 7,
    pageWidth: 1440,
    pageHeight: 810,
    template: "Popular",
  },
  "project-config": [],
  bmtConfig: [],
  videoList: [],
  staticAd: { haveAd: false },
  language: [
    {
      language: "English",
      btnFirstPage: "First",
      btnNextPage: "Next Page",
      btnLastPage: "Last",
      btnPrePage: "Previous Page",
      btnDownload: "Download",
      btnPrint: "Print",
      btnSearch: "Search",
      btnClearSearch: "Enter key to search",
      frmSearchPrompt: "Clear",
      btnBookMark: "Table of content",
      btnHelp: "Help",
      btnHome: "Home",
      btnFullscreen: "Fullscreen",
      btnSoundOn: "Sound On",
      btnSoundOff: "Sound Off",
      btnShareEmail: "Email",
      btnSocialShare: "Social Share",
      btnZoomIn: "Zoom In",
      btnZoomOut: "Zoom Out",
      btnDragToMove: "Move by mouse drag",
      btnAutoFlip: "Auto Flip",
      btnStopAutoFlip: "Stop Auto Flip",
      btnGoToHome: "Return Home",
      frmHelpCaption: "Help",
      frmHelpTip1: "Double click to zoom in or out",
      frmHelpTip2: "Drag the page corner to view",
      frmPrintCaption: "Print",
      frmPrintBtnCaption: "Print",
      frmPrintPreparePage: "Preparing Page:",
      frmPrintPrintFailed: "Print Failed:",
      pnlSearchInputInvalid: "The search text is too short.",
      loginCaption: "Login",
      loginInvalidPassword: "Not a valid password!",
      loginPasswordLabel: "Password:",
      loginBtnLogin: "Login",
      loginBtnCancel: "Cancel",
      btnThumb: "Thumbnails",
      lblPages: "Pages:",
      lblPagesFound: "Pages:",
      lblPageIndex: "Page",
      btnAbout: "About",
      frnAboutCaption: "About & Contact",
      btnSinglePage: "Single Page",
      btnDoublePage: "Double Page",
      tipChangeLanguage: "Please select a language below...",
      btnMoreOptionsRight: "More Options",
      btnFit: "Fit Window",
      smallModeCaption: "Click to view in fullscreen",
      btnAddAnnotation: "Add Annotations",
      btnAnnotation: "Annotations",
      FlipPageEditor_SaveAndExit: "Save and Exit",
      FlipPageEditor_Exit: "Exit",
      DrawToolWindow_Redo: "Redo",
      DrawToolWindow_Undo: "Undo",
      DrawToolWindow_Clear: "Clear",
      DrawToolWindow_Brush: "Brush",
      DrawToolWindow_Width: "Width",
      DrawToolWindow_Alpha: "Alpha",
      DrawToolWindow_Color: "Color",
      DrawToolWindow_Eraser: "Eraser",
      DrawToolWindow_Rectangular: "Rectangular",
      DrawToolWindow_Ellipse: "Ellipse",
      TStuff_BorderWidth: "Border Width",
      TStuff_BorderAlph: "Border Alpha",
      TStuff_BorderColor: "Border Color",
      DrawToolWindow_TextNote: "Text Note",
      AnnotMark: "Bookmarks",
      lastpagebtnHelp: "Last page",
      firstpagebtnHelp: "First page",
      aboubtnHelp: "About",
      screenbtnHelp: "Open this application in full-screen mode",
      helpbtnHelp: "Show help",
      searchbtnHelp: "Search from pages",
      pagesbtnHelp: "Take a look at the thumbnail of this brochure",
      bookmarkbtnHelp: "Open Bookmarks",
      AnnotmarkbtnHelp: "Open Table of content",
      printbtnHelp: "Print the brochure",
      soundbtnHelp: "Turn on or off the sound",
      sharebtnHelp: "Send Email to",
      socialSharebtnHelp: "Social Share",
      zoominbtnHelp: "Zoom in",
      downloadbtnHelp: "Downdlaod this brochure",
      pagemodlebtnHelp: "Switch Single and double page mode",
      languagebtnHelp: "Switch Lauguage",
      annotationbtnHelp: "Add Annotation",
      addbookmarkbtnHelp: "Add Bookmark",
      removebookmarkbtnHelp: "Remove Bookmark",
      updatebookmarkbtnHelp: "Update Bookmark",
      btnShoppingCart: "Shopping Cart",
      Help_ShoppingCartbtn: "Shopping Cart",
      Help_btnNextPage: "Next page",
      Help_btnPrePage: "Previous page",
      Help_btnAutoFlip: "Auto filp",
      Help_StopAutoFlip: "Stop atuo filp",
      btnaddbookmark: "Add",
      btndeletebookmark: "Delete",
      btnupdatebookmark: "Update",
      frmyourbookmarks: "Your bookmarks",
      frmitems: "items",
      DownloadFullPublication: "Full Publication",
      DownloadCurrentPage: "Current Page",
      DownloadAttachedFiles: "Attached Files",
      btnCopy: "Copy Button",
      infCopyToClipboard: "Your browser does not support clipboard.",
      restorePage: "Would you like to restore your previous session?",
      tmpl_Backgoundsoundon: "Background Sound On",
      tmpl_Backgoundsoundoff: "Background Sound Off",
      tmpl_Flipsoundon: "Flip Sound On",
      tmpl_Flipsoundoff: "Flip Sound Off",
      Help_PageIndex: "The current page number",
      tmpl_PrintPageRanges: "PAGE RANGES",
      tmpl_PrintPreview: "PREVIEW",
      btnSelection: "Select Text",
      loginNameLabel: "Name:",
      btnGotoPage: "Go",
      btnSettings: "Setting",
      soundSettingTitle: "Sound Setting",
      closeFlipSound: "Close Flip Sound",
      closeBackgroundSound: "Close Backgorund Sound",
      frmShareCaption: "Share",
      frmShareLinkLabel: "Link:",
      frmShareBtnCopy: "Copy",
      frmShareItemsGroupCaption: "Social Share",
      frmPanelTitle: "Share it",
      frmShareQRcode: "QRCode",
      TAnnoActionPropertyStuff_GotoPage: "Go to page",
      btnPageBack: "Backward",
      btnPageForward: "Forward",
      SelectTextCopy: "Copy Selected Text",
      selectCopyButton: "Copy",
      TStuffCart_TypeCart: "Shopping Cart",
      TStuffCart_DetailedQuantity: "Quantity",
      TStuffCart_DetailedPrice: "Price",
      ShappingCart_Close: "Close",
      ShappingCart_CheckOut: "Checkout",
      ShappingCart_Item: "Item",
      ShappingCart_Total: "Total",
      ShappingCart_AddCart: "Add to cart",
      ShappingCart_InStock: "In Stock",
      TStuffCart_DetailedCost: "Shipping cost",
      TStuffCart_DetailedTime: "Delivery time",
      TStuffCart_DetailedDay: "day(s)",
      ShappingCart_NotStock: "Not enough in stock",
      btnCrop: "Crop",
      btnDragButton: "Drag",
      btnFlipBook: "Flip Book",
      btnSlideMode: "Slide Mode",
      btnSinglePageMode: "Single Page Mode",
      btnVertical: "Vertical Mode",
      btnHotizontal: "Horizontal Mode",
      btnClose: "Close",
      btnBookStatus: "Book View",
      checkBoxInsert: "Insert Current Page",
      lblLast: "This is the last page.",
      lblFirst: "This is the first page.",
      lblFullscreen: "Click to view in fullscreen",
      lblName: "Name",
      lblPassword: "Password",
      lblLogin: "Login",
      lblCancel: "Cancel",
      lblNoName: "User name can not be empty.",
      lblNoPassword: "Password can not be empty.",
      lblNoCorrectLogin: "Please enter the correct user name and password.",
      btnVideo: "VideoGallery",
      btnSlideShow: "SlideShow",
      btnPositionToMove: "Move by mouse position",
      lblHelp1: "Drag the page corner to view",
      lblHelp2: "Double click to zoom in, out",
      lblCopy: "Copy",
      lblAddToPage: "add to page",
      lblPage: "Page",
      lblDescription: "Title",
      lblEdit: "Edit",
      lblDelete: "Delete",
      lblRemoveAll: "RemoveAll",
      tltCursor: "cursor",
      tltAddHighlight: "add highlight",
      tltAddTexts: "add texts",
      tltAddShapes: "add shapes",
      tltAddNotes: "add notes",
      tltAddImageFile: "add image file",
      tltAddSignature: "add signature",
      tltAddLine: "add line",
      tltAddArrow: "add arrow",
      tltAddRect: "add rect",
      tltAddEllipse: "add ellipse",
      lblDoubleClickToZoomIn: "Double click to zoom in.",
      frmShareLabel: "Share",
      frmShareInfo:
        "You can easily share this publication to social networks.Just cilck the appropriate button below.",
      frminsertLabel: "Insert to Site",
      frminsertInfo:
        "Use the code below to embed this publication to your website.",
      btnQRCode: "Click to scan QR code",
      btnRotateLeft: "Rotate Left",
      btnRotateRight: "Rotate Right",
      lblSelectMode: "Select view mode please.",
      frmDownloadPreview: "Preview",
      frmDownload: "Download",
      frmHowToUse: "How To Use",
      lblHelpPage1: "Move your finger to flip the book page.",
      lblHelpPage2: "Zoom in by using gesture or double click on the page.",
      lblHelpPage3:
        "Click on the logo to reach the official website of the company.",
      lblHelpPage4:
        "Add bookmarks, use search function and auto flip the book.",
      lblHelpPage5: "Switch horizontal and vertical view on mobile devices.",
      TTActionQuiz_PlayAgain: "Do you wanna play it again",
      TTActionQuiz_Ration: "Your ratio is",
      frmTelephone: "Telephone list",
      btnDialing: "Dialing",
      lblSelectMessage: "Please copy the the text content in the text box",
      btnSelectText: "Select Text",
      btnNote: "Annotation",
      btnPhoneNumber: "Telephone",
      btnWeCharShare: "WeChat Share",
      btnMagnifierIn: "Magnifying Glass",
      btnMagnifierOut: "Magnifier Reduction",
      frmShareSmallProgram: "smallProgram",
      btnMagnifier: "Magnifier",
      frmPrintPrintLimitFailed: "Sorry, you can't print the pages.",
      infNotSupportHtml5:
        "HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.",
      btnReport: "Report",
      btnDoubleSinglePage: "Page switch",
      btnDownloadPosterPrompt: "Click to download the poster",
      infLongPressToSavePoster:
        "Press and hold the mobile terminal to save the poster",
      infLongPressToIndentify: "Long press to identify QR code",
      infScanCodeToView: "Scan code to read",
      frmaboutcaption: "Contact",
      frmaboutDESCRIPTION: "Description",
      frmaboutAUTHOR: "Author",
      frmaboutADDRESS: "Address",
      frmaboutEMAIL: "Email",
      frmaboutWEBSITE: "Website",
      frmaboutMOBILE: "Mobile",
      infDeleteNote: "Do you want to delete the note?",
      proFullScreenWarn:
        "Current browser does not support full-screen,Please use Chrome for best results",
      btnBack: "Backs",
      frmVideoListTitle: "Video list",
      frmVideoTitle: "Video",
      lblConfirm: "Confirm",
      frmBookMark: "Book Mark",
      btnExitFullscreen: "Exit fullscreen",
      btnMore: "More",
      frmPrintall: "Print All Pages",
      frmPrintcurrent: "Print Current Page",
      frmPrintRange: "Print Range",
      frmPrintexample: "Example: 2,3,5-10",
      frmPrintbtn: "Print",
      frmaboutcontactinformation: "Contact Information",
      frmSearch: "Search",
      frmToc: "Table of Contents",
      btnTableOfContent: "Show Table of Contents",
      frmLinkLabel: "Link",
      frmQrcodeCaption:
        "Scan the bottom two-dimensional code to view with mobile phone.",
      btnLanguage: "Change Language",
      msgConfigMissing:
        "Configuration file is missing, unable to open the book.",
      lblSave: "Save",
      accessRestrictedTitle: "Access Restricted",
      enterYourName: "Enter your name",
      enterVisitCode: "Please enter your password",
      enterReadingCode: "enter your reading code",
      enterTheReason: "Enter your reason for application",
      enterPhoneNumber: "Enter your email address",
      enterVerificationCode: "Enter your verification code",
      getVerificationCode: "Send",
      sendValidCodeSuccess: "Verification code sent",
      getVerificationCodePrompt: "Get a verification code sent to your email",
      enterPasswordPrompt: "Password required to proceed reading",
      leaveMsgSimilarBooks: "Explore More Books",
      leaveMsgToAuthor: "Contact Author",
      leaveMsgName: "Your Name",
      leaveMsgContact: "Your Contact Information (visible only to the author)",
      leaveMsgEnter: "Please Enter the Message",
      leaveMsgCancel: "Cancel",
      leaveMsgCommitTitle: "Submit",
      leaveMsgPrompt: "We will forward your message to the book uploader.",
      leaveMsgErrorPrompt: "Exception occurred. Please try again later",
      readingCodeErrorPrompt: "Invalid reading code. Please try again",
      passwordErrorPrompt: "Invalid password. Please try again",
      invalidPhoneNumber: "Invalid number. Please try again",
      invalidEmail: "Invalid Email. Please try again",
      verificationCodeErrorPrompt:
        "Invalid verification code. Please try again",
      codeSendingFrequent: "Frequent operation, please try again later",
      commiteTitle: "Verify",
      shamStopTitle:
        "The author's account privileges have resulted in book access suspension.",
      shamStopSubTitle:
        "Contact <a target='_blank' href='{%host}/homepage/{%uLink}/' style='text-decoration: underline' >the author</a> for further information.",
      shamStopLeavePrompt: "Please complete the question.",
      shamStopLeaveMsgSuccessPrompt: "Send successfully",
      codeSending: "Sending",
      viewFullScreen: "Fullscreen",
      cardsSign: "click to view card",
      frmaboutViews: "Views",
      btnMessage: "Message",
      btnInstructions: "instructions",
      btnArticlePages: "Pages",
      btnArticleList: "Articles",
      btnCalendar: "Calendar",
      btnBook: "Book",
      btnEnlarge: "Enlarge",
      btnReduce: "Reduce",
      btnPrevArticle: "Prev Article",
      btnNextArticle: "Next Article",
      copySuccessfully: "Copy Successfully",
      cardsWechat: "Wechat",
      cardsTelephone: "phone",
      close: "close",
      jumpPageByEnterNumber:
        "Enter the page number to jump quickly to the specified page",
      jump: "Jump",
      relatedContent: "related information",
      brandTitleUndefined: "No brand name is set yet",
      more: "More",
      fold: "Put away",
      otherWorks: "other works",
      flipSound: "page turning sound",
      backgroundSound: "Background music",
      report: "report",
      copySuccessTip: "copy successfully",
      saveSuccessTip: "Saved successfully",
      scanCodeAddMy: "After saving, WeChat scan the code and add my friend",
      saveImg: "save Picture",
      searchTheBook: "Search this book content",
      historicalRecord: "history record",
      searchResultCount: "A total of {%count} results",
      noRelevantResults: "No relevant results",
      changeTheKeyWords: "Try another keyword ~",
      leastWordsTip: "Please enter at least 2 words",
      jumpPageInputTip:
        "Enter the page number to jump quickly to the specified page",
      jumpto: "Jump to",
      foldThumbnailTip: "Click here to put away the thumbnail ~",
      btnLoadingText: "In loading, it's fine soon",
      btnTitleText: "Read now",
      relatedInfoText: "Related Information",
      brandContactFrTitle: "Contact the author",
      shareFromPage: "Share starting from page N",
      TStuffShowInformatin_Width: "Background width",
      TStuffShowInformatin_Height: "Background height",
      TPageList_BlankPage: "Blank page",
      morePanelBookLink: "Link",
      morePanelPoster: "Poster",
      morePanelOtherShare: "Other",
      doublePageTitle: "Rotate the phone to enable double-page reading mode",
      doublePageDescription: "How to set landscape ?",
      doublePageGotIt: "Got it",
      doublePageAndroidSettingStep1: "1.The phone allows auto-rotation",
      doublePageAndroidSettingStep2:
        "2.The browser for reading e-books needs to be set to allow horizontal screen",
      doublePageAndroidSettingStep3:
        "3.Reading books with mobile phone turned sideways",
      doublePageIPhoneSettingStep1: "1.Phone portrait orientation lock off",
      doublePageIPhoneSettingStep2:
        "2.Reading books with mobile phone turned sideways",
      noFilesAvailablePrompt: "No Files Available!",
    },
  ],
  ols: [],
  slideshow: [],
  pageEditor: [],
  flipByAudio: null,
  downloadconfig: {
    pdf: null,
    isDownloadProject: false,
    isDownloadAttach: false,
    attachments: [],
    hideDownloadSinglePage: false,
  },
  assistantConfig: null,
  phoneNumber: [],
  bookPlugin: null,
  fliphtml5_pages: [
    {
      n: ["a0117f8fadc1c49dc2470c024498abb4.webp"],
      t: "./files/thumb/23608b1c5718c3a1247de5ab979ad4e4.webp",
    },
    {
      n: ["ff11499f0bebdfa1924693018781f2fe.webp"],
      t: "./files/thumb/87ee0923f2e2dcfe9e041bba927528c8.webp",
    },
    {
      n: ["603259bf524e69866646d744ba4e3259.webp"],
      t: "./files/thumb/c31ae8cd1f5bb15eac790048aa7bd899.webp",
    },
    {
      n: ["b4002cb4406298852d2d9a2ef5af92e3.webp"],
      t: "./files/thumb/e526a62ae0f7700271fdca92178597af.webp",
    },
    {
      n: ["0fc86f6871c234990829794b4a96275a.webp"],
      t: "./files/thumb/b81f57ec0688d3d665bf5fead13bf18b.webp",
    },
    {
      n: ["cef393dba81461d558ffac4de7e87eb6.webp"],
      t: "./files/thumb/2432e6dabed387ead5617dfc9eec9acc.webp",
    },
    {
      n: ["41fc30c49041b651a2ea9323ccc6d739.webp"],
      t: "./files/thumb/c4b281ae1c9409c28fad40a70fcb4484.webp",
    },
  ],
  downloadConfig: null,
  fileExist: { pageEditor: 0, plugin: 0 },
  loadingConfig: {
    loadingBackground: "#323232",
    loadingCaptionColor: "#DDDDDD",
    loadingCaption: "",
    loadingCaptionFontSize: "20",
    loadingPicture: "",
    loadingPictureHeight: "150",
    showLoadingGif: "Yes",
    loadingVideo: "",
    loadingDisplayTime: "0",
  },
};
